### ISSUE TITLE
Get-WebCreator - exception for field or property Audit

### ISSUE THREAD

**Issue by mmrk3** [InstantQuick/InstantQuick-SharePoint-Provisioning#1]
Hi Doug,

I am using Get-WebCreator command to get the manifest for my source web site and am getting an error.  The server library version is "15.0.4569.1501".  

**This is the command** 
`Get-WebCreator -SourceClientContext $sourceCtx -BaseClientContext $baseCtx -Options $options -AppManifest $McKNetMan -VerboseNotify`

**Error -**

This is a root web.
Exception calling "GetWebCreatorBuilder" with "4" argument(s): "Field or property "Audit" does not exist."
At C:\Program Files (x86)\SharePointProvisioning\IQAppProvisioningModule\IQAppProvisioningModule.psm1:855 char:4
-             $builder.GetWebCreatorBuilder($AppManifest, $Options, $SourceClientContext, $ ...
-    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
  - FullyQualifiedErrorId : ServerException

**Comment by douglasware** [comment]
Thanks Meenu!

**Comment by douglasware** [comment]
It looks like the properties weren't added to CSOM until the April 2014 CU. Please patch your farm and try again. I was able to confirm this is a problem with SP1 (which is your server version), but not with more recent updates.
